version: '3.8'

services:
  ms-competencies:
    build:
      context: ../../../backend/ms-competencies
    container_name: ms-competencies
    ports:
      - "8010:8010"
    volumes:
      - ../../../backend/ms-competencies:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=competencies_db
      - DB_USER=competencies_user
      - DB_PASSWORD=competencies_password
      - DB_HOST=competencies-db
      - DB_PORT=5432
    networks:
      - sportboard-network

  competencies-db:
    image: postgres:15
    container_name: competencies-db
    restart: always
    environment:
      POSTGRES_USER: competencies_user
      POSTGRES_DB: competencies_db
      POSTGRES_PASSWORD: competencies_password
    volumes:
      - competencies-db-data:/var/lib/postgresql/data
    networks:
      - sportboard-network

networks:
  sportboard-network:
    external: true

volumes:
  competencies-db-data: